### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by trautamaki** [lineage-next/android_packages_apps_Catapult#3]
- [ ] Remove/add channel row when app installed/uninstalled
- [ ] Ask to be set default launcher
- [x] Assistant?
- [ ] Notification
- [ ] Recents, if possible

**Comment by SebaUbuntu** [comment]
> Remove/add channel row when app installed/uninstalled

I'm guessing this one is done automatically with flows now?

**Comment by trautamaki** [comment]
![image](https://github.com/user-attachments/assets/438fbbd9-923a-4f97-9646-5498f67605ba)
